language: "python"
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - "pip install -r tests/requirements.txt"
    - "pip install -e ."
script:
    - "py.test tests"
after_success:
    - "coveralls"
notifications:
    email: false
